academic_manager/courses/routes.py
from flask import redirect, url_for, render_template, request, session, flash, Blueprint, abort
from academic_manager.extensions import restricted
from flask_login import current_user, login_required
from academic_manager.courses.forms import CourseForm, TaskForm
from academic_manager.main.utilities import *
from academic_manager.courses.utilities import *
from academic_manager.students.utilities import *


courses = Blueprint('courses', __name__, template_folder="templates", url_prefix="/courses")


@courses.route("/add-course/", methods=['POST', 'GET'])
@restricted(role=["admin", "teacher"])
def add_course():
    form = CourseForm()

    # create teachers list
    if current_user.is_admin:
        teachers_lst = [(teacher.id, teacher.full_name) for teacher in Teacher.query.all()]
        teachers_lst.insert(0, ('0', "Choose.."))
    else:
        teachers_lst = [(current_user.id, current_user.full_name)]

    if form.validate_on_submit():
        course_name = form.course.data
        teacher_id = form.teacher.data
        create_new_course(course_name, teacher_id)
        flash(f"The course '{course_name}' has been added", "success")
        return redirect(url_for("courses.add_course"))
    else:
        form.teacher.choices = teachers_lst

    return render_template("add_course.html", form=form, lst=teachers_lst)


@courses.route("/delete-course/<int:course_id>/")
@restricted(role=["admin", "teacher"])
def delete_course(course_id):
    current_course = Course.query.get_or_404(course_id)

    # Prevents teachers who do not teach the course from deleting it
    if current_user.is_teacher and current_course.lecturer != current_user:
        abort(403)

    course_name = current_course.course_name
    current_course.delete_from_db()
    flash(f"{course_name} has been deleted", "success")
    return redirect(request.referrer)


@courses.route("/dashboard/<int:course_id>/")
@courses.route("/dashboard/<int:course_id>/main/")
@login_required
def course_dashboard(course_id):
    course = Course.query.get_or_404(course_id)
    last_task = Task.query.filter_by(course_id=course_id).order_by(Task.date_posted.desc()).first()
    best_student = get_best_student(course_id)
    return render_template('dashboard_main.html', course=course, task=last_task, best_student=best_student)


@courses.route("/dashboard/<int:course_id>/add-task/", methods=['POST', 'GET'])
@restricted(role=["admin", "teacher"])
def dashboard_add_tasks(course_id):
    form = TaskForm()
    current_course = Course.query.get_or_404(course_id)
    teacher = current_course.lecturer

    # Prevents teachers who do not teach the course from add tasks
    if current_user.is_teacher and teacher != current_user:
        abort(403)

    if form.validate_on_submit():

        # Files handling
        if form.file.data:
            new_file_name = form.file_name.data if form.file_name.data else ""
            # Save the file in uploads folder
            file_name = save_file(form.file.data, new_file_name, course_id)
        else:
            file_name = None

        create_new_task(title=form.title.data, content=form.content.data, file_name=file_name,
                        course_id=current_course.id, teacher_id=teacher.id)

        flash(f"A new Task was added to {current_course.course_name} course ", "success")
        return redirect(url_for("courses.dashboard_view_tasks", course_id=course_id))

    return render_template('dashboard_task.html', course=current_course, form=form,
                           page_name="New Task")


@courses.route("/dashboard/delete_task/<int:task_id>/", methods=['POST', 'GET'])
@restricted(role=["admin", "teacher"])
def dashboard_delete_task(task_id):
    current_task = Task.query.get_or_404(task_id)
    teacher = current_task.course.lecturer

    # Prevents teachers who do not teach the course from deleting tasks
    if current_user.is_teacher and teacher != current_user:
        abort(403)

    title = current_task.title
    course = current_task.course
    current_task.delete_from_db()
    flash(f"Task '{title}' was successfully deleted from {course.course_name}", "success")
    return redirect(url_for('courses.dashboard_view_tasks', course_id=course.id))


@courses.route("/dashboard/<int:course_id>/update-task/<int:task_id>/", methods=['POST', 'GET'])
@restricted(role=["admin", "teacher"])
def dashboard_edit_task(course_id, task_id):
    form = TaskForm()
    current_task = Task.query.get_or_404(task_id)
    current_course = Course.query.get_or_404(course_id)
    teacher = current_course.lecturer

    # Prevents teachers who do not teach the course from edit tasks
    if current_user.is_teacher and teacher != current_user:
        abort(403)

    if form.validate_on_submit():

        # Files handling
        if form.file.data:
            new_file_name = form.file_name.data if form.file_name.data else ""
            # Save the file in uploads folder
            file_name = save_file(form.file.data, new_file_name, course_id)
            create_new_file(file_name, task_id)

        current_task.title = form.title.data
        current_task.content = form.content.data
        current_task.add_update_time()
        db.session.commit()
        flash(f"Your Task has been update! ", "success")
        return redirect(url_for("courses.dashboard_view_tasks", course_id=course_id))

    elif request.method == "GET":
        form.title.data = current_task.title
        form.content.data = current_task.content

    return render_template('dashboard_task.html', course=current_course, form=form,
                           page_name="Edit Task")


@courses.route("/dashboard/<int:course_id>/view-tasks/")
@login_required
def dashboard_view_tasks(course_id):
    current_course = Course.query.get_or_404(course_id)
    tasks = Task.query.filter_by(course_id=course_id).order_by(Task.date_posted.desc()).all()
    return render_template("dashboard_view_tasks.html", course=current_course, tasks=tasks)


@courses.route("/dashboard/<int:course_id>/view-task/<int:task_id>")
@login_required
def dashboard_single_task(course_id, task_id):
    current_task = Task.query.get_or_404(task_id)
    current_course = Course.query.get_or_404(course_id)
    return render_template("dashboard_single_task.html", course=current_course, task=current_task)


@courses.route("/dashboard/<int:course_id>/participants")
@login_required
def dashboard_participants(course_id):
    current_course = Course.query.get_or_404(course_id)
    return render_template("dashboard_participants.html", course=current_course)


@courses.route("/dashboard/<int:course_id>/grades/", methods=['POST', 'GET'])
@restricted(role=["admin", "teacher"])
def dashboard_update_grades(course_id):
    current_course = Course.query.get_or_404(course_id)
    teacher = Teacher.query.get(current_course.teacher_id)

    # Prevents teachers who do not teach the course from edit grades
    if current_user.is_teacher and teacher != current_user:
        abort(403)

    if request.method == "POST":
        for enroll in current_course.enrollment:
            new_grade = request.form[str(enroll.id)]
            if new_grade:
                enroll.grade = new_grade
        db.session.commit()
        return redirect(request.referrer)

    return render_template("dashboard_update_grades.html", course=current_course)


@courses.route("/dashboard/<int:course_id>/remove-file/<int:file_id>/")
@restricted(role=["admin", "teacher"])
def remove_file(course_id, file_id):
    current_course = Course.query.get_or_404(course_id)
    file = File.query.get_or_404(file_id)

    # Prevents teachers who do not teach the course from remove files
    if current_user.is_teacher and current_course.lecturer != current_user:
        abort(403)

    file_name = file.name
    file.delete_from_db()
    flash(f"{file_name} has been deleted", "success")
    return redirect(request.referrer)

academic_manager/courses/templates/add_course.html
{% extends "base.html" %}
{% block title %}Add Course{% endblock %}
{% block content %}
<div class="card">
    <h5 class="card-header">Add Course</h5>
    <div class="card-body">
        <form action="#" method="post">
            {{ form.hidden_tag() }}

            <fieldset class="form-group">

                <!-- Teacher Name -->
                <div class="form-group">
                    <div>{{ form.teacher.label(class="form-control-label") }}:</div>
                    {{ form.teacher(class="form-control-label", value=lst) }}
                </div>

                <!-- Course Name -->
                <div class="form-group">
                    {{ form.course.label(class="form-control-label") }}
                    {% if form.course.errors %}
                        {{ form.course(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.course.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.course(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>

            <!-- Submit -->
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

academic_manager/courses/templates/add_task.html
{% extends "base.html" %}
{% block title %}Add Task{% endblock %}
{% block content %}

<h5 class="card-header">{{ course.course_name }} - Add Task</h5>
<div class="card-body">

    <form action="#" method="post">
        <div class="form-group">
                <div class="form-group row">
                    <label for="course" class="col-sm-2">Course</label>
                    <div class="col-sm-2">
                       <input type="text" readonly min="0" max="100" class="form-control-plaintext" id="course"
                              value="{{ course.course_name }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputTitle" class="col-sm-2 col-form-label">
                        Title:</label>
                    <div class="col-sm-8">
                       <input type="text" name="title" class="form-control" id="inputTitle"
                       placeholder="Task Title" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputContent" class="col-sm-2 col-form-label">
                        Content:</label>
                    <div class="col-sm-8">
                        <textarea  type="text" name="content" class="form-control"
                                   style=" height: 200px; white-space: nowrap;"
                                   placeholder="Enter your Task" id="inputContent"
                                   required></textarea>
                    </div>
                </div>
        </div>
        <br>
        <button type="submit" value="submit" class="btn btn-primary">Submit</button>
    </form>

</div>

{% endblock %}

academic_manager/courses/templates/course_dashboard_layout.html
{% extends "base.html" %}
{% block title %}{{ course.course_name }}{% endblock %}
{% block content %}


<div class="row">
    <div class="col-md-4">
        <div class="content-section">
            <h4>{{ course.course_name }}</h4>
            <p class='text-muted'>Dashboard</p>

            <ul class="list-group">
                <li class="list-group-item list-group-item-light">
                    <a href="{{ url_for('courses.course_dashboard', course_id=course.id) }}">
                        <i class="fas fa-chart-line fa-lg mr-2"></i>Main</a>
                </li>
                <li class="list-group-item list-group-item-light">
                    <a href="{{ url_for('courses.dashboard_participants', course_id=course.id) }}">
                        <i class="fas fa-users fa-lg mr-2"></i>Participants</a>
                </li>
                <li class="list-group-item list-group-item-light">
                    <a href="{{ url_for('courses.dashboard_view_tasks', course_id=course.id) }}">
                        <i class="fas fa-tasks fa-lg mr-2"></i>Tasks</a>
                </li>
                {% if current_user.is_admin or current_user.is_teacher %}
                <li class="list-group-item list-group-item-light">
                    <a href="{{ url_for('courses.dashboard_add_tasks', course_id=course.id) }}">
                        <i class="fas fa-pencil-alt fa-lg mr-2"></i>New Task</a>
                </li>
                <li class="list-group-item list-group-item-light">
                    <a href="{{ url_for('courses.dashboard_update_grades', course_id=course.id) }}">
                        <i class="fas fa-award fa-lg mr-2"></i>Grades</a>
                </li>
                {% endif %}
                <li class="list-group-item list-group-item-light">
                    <a href="#">
                        <i class="far fa-calendar fa-lg mr-2"></i> Calendar</a>
                </li>
            </ul>
            </p>
        </div>
    </div>
    <div class="col-md-8">
        {% block dashboard %}{% endblock %}
    </div>
</div>


{% endblock content %}

academic_manager/courses/templates/dashboard_main.html
{% extends "course_dashboard_layout.html" %}
{% block dashboard %}


<h2 class="mb-4"><i class="fas fa-chart-line mr-2"></i>Main Dashboard</h2>

<div class="content-section">
    <h5>Teacher: {{ course.lecturer.full_name }}</h5>
    <h6>There are {{ course.enrollment|length }} participants in this course.</h6><br><br>

    {% if best_student %}
    <strong>Outstanding student</strong>
    <p>Name: {{ best_student.full_name }} | Avg: {{ '%0.2f' % best_student.avg()|float }}</p>
    {% endif %}
</div>


<!- Last Task -->
{% if task %}
<h5 class="mb-4">Last Task</h5>
<article class="media content-section">
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pics/' + task.author.profile_img) }}">
    <div class="media-body">

        <div class="article-metadata">
            <a class="mr-2"
               href="{{ url_for('teachers.watch_teacher', user_id=task.author.id) if current_user.is_admin
               else url_for('main.profile', user_id=task.author.id)}}">{{ task.author.full_name }}</a>
            <small class="text-muted">{{ task.date_posted.strftime('%H:%M %b %d, %Y') }}</small>
        </div>

        <h2><a class="article-title"
               href="{{ url_for('courses.dashboard_single_task', course_id=course.id, task_id=task.id) }}">
            {{ task.title }}</a>
        </h2>

        <p class="article-content crop">
            {{ task.content}}
        </p>

        {% if task.content %}
            <a href="{{ url_for('courses.dashboard_single_task', course_id=course.id, task_id=task.id) }}">
            <i class="fas fa-angle-double-right"></i>
            </a>
        {% endif %}
        <br>
        {% if task.files %}
            <small class="text-muted"><i class="far fa-file-alt mr-2"></i>Attached Files ({{ task.files|length }})</small>
        {% endif %}
        <br>
        {% if task.update_time %}
            <small class="text-muted">
                Another edit was made at {{ task.update_time.strftime('%H:%M %b %d, %Y') }}
            </small>
        {% endif %}
    </div>
</article>
{% endif %}


{% endblock dashboard %}

academic_manager/courses/templates/dashboard_participants.html
{% extends "course_dashboard_layout.html" %}
{% block dashboard %}

<h2 class="mb-4"><i class="fas fa-users mr-2"></i>Participants ({{ course.enrollment|length }})</h2>

<table class="table" style="width: 100%;">
    <thead>
    <tr>
        <th scope="col">#</th>

        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        {% set teacher = course.lecturer %}
        <td scope="row" style="vertical-align: middle;"><i class="fas fa-chalkboard-teacher fa-lg"></i></td>
        <td scope="row" style="vertical-align: middle;">
            <a href="{{ url_for('teachers.watch_teacher', user_id=teacher.id)
                         if current_user.is_admin
                         else url_for('main.profile', user_id=teacher.id)}}">
                {{ teacher.full_name }}</a>
        </td>
        <td scope="row" style="vertical-align: middle;">{{ teacher.email }}</td>
        <td scope="row" style="vertical-align: middle;">
            <img class="rounded-circle article-img"
                 src="{{ url_for('static', filename='profile_pics/' + teacher.profile_img) }}">
        </td>
    </tr>

    {% for enroll in course.enrollment %}
    {% set student = enroll.student %}
    <tr>
        <td scope="row" style="vertical-align: middle;">{{ loop.index }}</td>
        <td scope="row" style="vertical-align: middle;">
            <a href="{{ url_for('students.watch_student', user_id=student.id)
                                if current_user.is_admin or current_user.is_teacher
                                else url_for('main.profile', user_id=student.id)}}">
                {{ student.full_name }}</a>
        </td>
        <td scope="row" style="vertical-align: middle;">{{ student.email }}</td>
        <td scope="row" style="vertical-align: middle;">
            <img class="rounded-circle article-img"
                 src="{{ url_for('static', filename='profile_pics/' + student.profile_img) }}">

            <!-- Delete student enrollment -->
            {% if current_user.is_admin or current_user == course.lecturer %}
            <a class="my-btn btn-del"
               href="{{ url_for('students.remove_enrollment',
                   user_id=student.id, enrollment_id=enroll.id) }}">
                <i class="fas fa-user-minus"></i>
            </a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>


{% endblock dashboard %}

academic_manager/courses/templates/dashboard_single_task.html
{% extends "course_dashboard_layout.html" %}
{% block dashboard %}

<article class="media content-section">
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pics/' + task.author.profile_img) }}">
    <div class="media-body">

        <div class="article-metadata">
            <a class="mr-2"
               href="{{ url_for('teachers.watch_teacher', user_id=task.author.id) if current_user.is_admin
               else url_for('main.profile', user_id=task.author.id)}}">{{ task.author.full_name }}</a>
            <small class="text-muted">{{ task.date_posted.strftime('%H:%M %b %d, %Y') }}</small>

            {% if current_user.is_admin or current_user.is_teacher %}
            <div style="float: right;">
                <a class="my-btn btn-edit"
                   href="{{ url_for('courses.dashboard_edit_task', course_id=course.id, task_id=task.id) }}">
                    <i class="fas fa-edit"></i></a>

                <!-- Button trigger modal -->
                <a class="my-btn btn-del" data-toggle="modal" data-target="#deleteTaskModal">
                    <i class="fas fa-trash-alt"></i></a>
            </div>
            {% endif %}

        </div>

        <h2><a class="article-title" href="#">{{ task.title }}</a></h2>
        <p class="article-content">{{ task.content }}</p>

        {% for file in task.files %}
            <a href="{{ url_for('static', filename='uploads/' + file.path) }}">
                <i class="far fa-file-alt mr-2"></i>{{ file.name }}</a>

            {%- if current_user.is_admin or current_user.is_teacher -%}
                <!-- Button trigger modal -->
                <a class="my-btn btn-del" href="{{ url_for('courses.remove_file', course_id=course.id, file_id=file.id) }}">
                    <i class="far fa-times-circle ml-4 mr-1"></i></a>
            {%- endif -%}
            <br>
        {% endfor %}
        <br>
        {% if task.update_time %}
        <small class="text-muted">Another edit was made at {{ task.update_time.strftime('%H:%M %b %d, %Y') }}
            {% endif %}
        </small>


    </div>
</article>


<!-- Task Modal -->
<div class="modal fade" id="deleteTaskModal" tabindex="-1" aria-labelledby="deleteTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteTaskModalLabel">Delete Task</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this task?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a type="button" class="btn btn-danger"
                   href="{{ url_for('courses.dashboard_delete_task', task_id=task.id) }}">Delete</a>
            </div>
        </div>
    </div>
</div>


{% endblock dashboard %}

academic_manager/courses/templates/dashboard_task.html
{% extends "course_dashboard_layout.html" %}
{% block dashboard %}

<h2 class="mb-4"><i class="fas fa-pencil-alt mr-2"></i>{{ page_name }}</h2>

<div class="content-section">
            <form action="#" method="post" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <!-- Title -->
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control") }}
                    {% endif %}
                </div>

                <!-- Content -->
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {{ form.content(class="form-control", id="editor", rows="8", cols="50") }}
                </div>

                <!-- File -->
                <div class="form-group">
                    {{ form.file.label() }}:
                    {{ form.file(class="form-control-file  form-control-sm") }}
                    {% if form.file.errors %}
                            {% for error in form.file.errors %}
                                <span class="text-danger">{{ error }}</span></br>
                            {% endfor %}
                    {% endif %}
                </div>

                <!-- File Name -->
                <div class="form-group">
                    {{ form.file_name.label(class="form-control-label") }}
                    {% if form.file_name.errors %}
                        {{ form.file_name(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.file_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.file_name(class="form-control") }}
                        <small class="form-text text-muted">Note: The file name must be in English.<br>
                        If the file you uploaded is not in English please write a new name.</small>
                    {% endif %}
                </div>

            </fieldset>

            <!-- Submit -->
            <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
</div>

{% endblock dashboard %}

academic_manager/courses/templates/dashboard_update_grades.html
{% extends "course_dashboard_layout.html" %}
{% block dashboard %}


<h2 class="mb-4"><i class="fas fa-award mr-2"></i>Grades</h2>


<form action="#" method="post">
        <div>

        <small class='text-muted'>{{ course.enrollment|length }} Participants:</small>
        <!-- Submit -->
        <button type="submit" value="Submit" class="btn btn-outline-info btn-sm mb-2" style="float: right;">Submit</button>

    </div>
    <table class="table" style="width: 100%;">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Grade</th>
            <th scope="col">Update</th>
        </tr>
        </thead>
        <tbody>

        {% for enroll in course.enrollment %}
        {% set student = enroll.student %}
        <tr>
            <td scope="row">{{ loop.index }}</td>
            <td scope="row">
                <a href="{{ url_for('students.watch_student', user_id=student.id)
                                if current_user.is_admin or current_user.is_teacher
                                else url_for('main.profile', user_id=student.id)}}">
                    {{ student.full_name }}</a>
            </td>
            <td scope="row">{{ enroll.grade if enroll.grade else "-" }}</td>
            <td scope="row">
                <input type="number" name="{{ enroll.id }}" min="0" max="100"
                       class="form-control" value="{{ enroll.grade }}">
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- Submit -->
    <div class="form-group">
        <button type="submit" value="Submit" class="btn btn-outline-info">Submit</button>
    </div>
</form>

{% endblock dashboard %}

academic_manager/courses/templates/dashboard_view_tasks.html
{% extends "course_dashboard_layout.html" %}
{% block dashboard %}

{% if tasks %}
<h2 class="mb-4"><i class="fas fa-tasks mr-2"></i>Tasks ({{ tasks|length }})</h2>
{% for task in tasks %}
<article class="media content-section">
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pics/' + task.author.profile_img) }}">
    <div class="media-body">

        <div class="article-metadata">
            <a class="mr-2"
               href="{{ url_for('teachers.watch_teacher', user_id=task.author.id) if current_user.is_admin
               else url_for('main.profile', user_id=task.author.id)}}">{{ task.author.full_name }}</a>
            <small class="text-muted">{{ task.date_posted.strftime('%H:%M %b %d, %Y') }}</small>
        </div>

        <h2>
            <a class="article-title"
               href="{{ url_for('courses.dashboard_single_task', course_id=course.id, task_id=task.id) }}">
                {{ task.title }}</a>
        </h2>

        <p class="article-content crop">
            {{ task.content}}
        </p>

        {% if task.content %}
            <a href="{{ url_for('courses.dashboard_single_task', course_id=course.id, task_id=task.id) }}">
            <i class="fas fa-angle-double-right"></i>
            </a>
        {% endif %}
        <br>
        {% if task.files %}
            <small class="text-muted"><i class="far fa-file-alt mr-2"></i>Attached Files ({{ task.files|length }})</small>
        {% endif %}
        <br>
        {% if task.update_time %}
            <small class="text-muted">
                Another edit was made at {{ task.update_time.strftime('%H:%M %b %d, %Y') }}
            </small>
        {% endif %}
    </div>
</article>

{% endfor %}

{% else %}
<div class="content-section text-center">
    <h4 class="my-3">There are no tasks..</h4>
    <a href="https://www.google.com/search?q=beach+near+me&oq=beatch+ne&aqs=chrome.1.69i57j0.5055j0j1&sourceid=chrome&ie=UTF-8"
       class='text-muted'><i class="fas fa-umbrella-beach fa-4x my-4"></i><br>you can go to the beach</a>
</div>

{% endif %}


{% endblock dashboard %}