academic_manager/main/routes.py
from flask import redirect, render_template, request, flash, Blueprint, url_for, current_app
from flask_login import login_user, current_user, logout_user, login_required
from academic_manager.extensions import bcrypt, restricted
from academic_manager.main.forms import (RegistrationForm, LoginForm, UpdateUserForm, ProfilePictureForm,
                                         ResetPasswordForm, ResetPasswordRequestForm)
from academic_manager.main.utilities import *
from academic_manager.students.utilities import *
from datetime import datetime
from academic_manager.models import User
from academic_manager.main.db_init import init_db

main = Blueprint('main', __name__, template_folder="templates")


@main.route("/init_db")
def main_db_init():
    init_db()
    return redirect(url_for("main.home"))


@main.route("/")
@main.route("/home/")
def home():
    if current_user.is_authenticated:
        best_student = get_best_student()
        current_date = datetime.now()
        return render_template("home.html", best_student=best_student, current_date=current_date)
    else:
        return render_template("index.html")


@main.route("/login/", methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        flash("Already logged in!", "warning")
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()

        # Validate the password if the user exist
        if user and bcrypt.check_password_hash(user.password, form.password.data):

            # Check if teacher ia approved by the admin
            if user.is_teacher and not user.approved:
                flash(f"{user.email} is not approved yet by the admin", "danger")
                return redirect(url_for("main.home"))

            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash("Logged in successfully!", "success")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))

        else:
            flash("The Email or Password is invalid", "danger")
            return redirect(url_for("main.login"))

    return render_template("login.html", form=form)


@main.route("/register/", methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        flash("Already logged in!", "warning")
        return redirect(url_for("main.home"))
    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        make_new_user(form.email.data, form.first_name.data, form.last_name.data,
                      hashed_password, form.gender.data, form.role.data)
        flash(f'Account created for {form.first_name.data}! You can login now', 'success')
        return redirect(url_for('main.login'))

    return render_template('register.html', form=form)


@main.route("/logout/")
@login_required
def logout():
    current_user.update_last_seen()
    logout_user()
    return redirect(url_for("main.home"))


@main.route("/profile/<int:user_id>")
@login_required
def profile(user_id):
    user = User.query.get_or_404(user_id)
    image_file = url_for('static', filename='profile_pics/' + user.profile_img)
    return render_template('profile.html', user=user, image_file=image_file)


@main.route("/update/<int:user_id>/", methods=['POST', 'GET'])
@restricted(role=["admin", "current_user"])
def update_user_profile(user_id):
    form = UpdateUserForm(user_id=user_id)
    user = User.query.get_or_404(user_id)

    if form.validate_on_submit():

        # Profile picture handling
        if form.picture.data:

            # Resize and save picture in users folder
            pic_file = save_picture(form.picture.data)

            # Removes the previous image from the repository
            remove_profile_picture(user.profile_img)
            user.profile_img = pic_file

        name = user.first_name
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.email = form.email.data.lower()
        user.gender = form.gender.data
        db.session.commit()

        flash(f"{name}'s profile has been updated!", 'success')
        return redirect(url_for('main.profile', user_id=user_id))

    elif request.method == 'GET':
        form.first_name.data = user.first_name
        form.last_name.data = user.last_name
        form.email.data = user.email
        form.gender.data = user.gender

    return render_template('update_user_profile.html', user=user, form=form)


@main.route("/profile-pic-gallery/", methods=['POST', 'GET'])
@login_required
def profile_picture_gallery():
    item_lst = os.listdir(os.path.join(current_app.root_path, 'static/profile_pics/default'))
    form = ProfilePictureForm()

    if form.validate_on_submit():
        remove_profile_picture(current_user.profile_img)
        current_user.profile_img = "default/" + form.images.data
        db.session.commit()

        flash('Your profile image has been updated!', 'success')
        return redirect(url_for('main.profile', user_id=current_user.id))

    elif request.method == "GET":
        form.images.choices = item_lst

    return render_template('profile_pic_gallery.html', form=form)


@main.route("/delete_user/<int:user_id>")
@restricted(role=["admin", "current_user"])
def delete_user(user_id):
    user_to_del = User.query.get_or_404(user_id)

    # User deleting his profile
    if current_user.id == user_id:
        logout_user()
        user_to_del.delete_from_db()
        flash("Your account has been deleted", "success")
        return redirect(url_for("main.home"))

    # Admin deleting other user profile
    if current_user.is_admin:
        flash(f"{user_to_del.email} has been deleted", "success")
        is_teacher = user_to_del.is_teacher
        user_to_del.delete_from_db()
        return redirect(url_for("admin.admin_teachers")) if is_teacher \
            else redirect(url_for("admin.admin_students"))


@main.route("/reset-password/", methods=['POST', 'GET'])
def reset_password_request():
    if current_user.is_authenticated:
        flash("Already logged in!", "warning")
        return redirect(url_for("main.home"))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_password_email(user)
        flash("An email has been sent to your account with password reset instructions.", "info")
        return redirect(url_for("main.login"))

    return render_template('reset_password_request.html', form=form)


@main.route("/reset-password/<token>/", methods=['POST', 'GET'])
def reset_password_token(token):
    if current_user.is_authenticated:
        flash("Already logged in!", "warning")
        return redirect(url_for("main.home"))

    user = User.verify_reset_password_token(token)
    if not user:
        flash("Your token is invalid or has expired", "warning")
        return redirect(url_for("main.reset_password_request"))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You can login now', 'success')
        return redirect(url_for('main.login'))
    return render_template('reset_password_token.html', form=form)

academic_manager/main/templates/home.html
{% extends "base.html" %}
{% block title %}Home page{% endblock %}

{% block content %}

    <div class="card">
        <h5 class="card-header">Hey, {{ current_user.first_name }}!</h5>
        <div class="card-body">
            <div class="media">
                <img src="{{ url_for('static', filename='/images/813810.png') }}"
                     class="align-self-center mr-3" width="200" height="170" alt="students">
                <div class="media-body">
                    <h5 class="mt-3">Remarks by the Chairman of the Student Association</h5>
                    <p>Hey everyone!! My name is Hadar and I am a senior from Nashville, TN.
                        I study Government with a secondary in Educational Studies and a language citation in Spanish.
                        I have worked in the Admissions Office with the Undergraduate Admissions Council (UAC) for all 4
                        years of college!
                    <p>When I am not working, you can usually find me hanging out with my blockmates (who are my best
                        friends),eating cheese, or spending time with young people through mentoring and tutoring programs!
                        On-campus, I am a member of Harvard Model Congress and the Asian American Womxn's Association.</p>
                </div>
            </div>
        </div>
    </div>
    <br>
    {% if best_student and best_student.avg() > 50 %}
        <div class="card">
            <div class="card-body media">
                <div class="media-body">
                    <h5 class="mt-4">Outstanding student this month</h5>
                    <p>Name: {{ best_student.full_name }} | Avg: {{ '%0.2f' % best_student.avg()|float }}</p>
                    <p>Congratulations to {{ best_student.first_name }} who received the best average for
                        {{ current_date.strftime('%B')}} and for that he received the Outstanding Student
                        Award of the month.</p><strong>Rise and Succeed!</strong>
                </div>
                <img src="{{ url_for('static', filename='/images/graduate-cap.jpg') }}"
                     class="ml-3" width="310" height="230" alt="graduate-cap">
            </div>
        </div>
    {% endif %}



{% endblock %}

academic_manager/main/templates/index.html
{% extends "base.html" %}
{% block title %}Home page{% endblock %}

{% block content %}
<div id="carouselIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselIndicators" data-slide-to="1"></li>
        <li data-target="#carouselIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{{ url_for('static', filename='/images/home_img_3.jpg') }}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Welcome To the Academic Manager!</h5>
                <p>Here you can manage all the users in the college.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{{ url_for('static', filename='/images/home_img_1.jpg') }}" class="d-block w-100 h-90" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>In the Academic Manager</h5>
                <p>Experiential Learning , Applied Research and Social Commitment.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{{ url_for('static', filename='/images/home_img_2.jpg') }}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Social life in college</h5>
            </div>
        </div>
    </div>
  <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<div class="content-section text-center my-4">
    <h3>Hey, {{ current_user.first_name if current_user.is_authenticated else "friend" }}!</h3>
    <h5 class="mt-4">Welcome To the Academic Manager</h5>
    <p>Please Login\Sign-up with the Academic's email address.</p>
    <div class="mt-4">
        <a href="{{ url_for('main.login') }}" class="btn btn-outline-secondary mt-4"><i class="fas fa-sign-in-alt mr-2"></i>Login</a>
        <a href="{{ url_for('main.register') }}" class="btn btn-outline-info mt-4"><i class="fas fa-user-plus mr-2"></i>Register</a>
    </div>
</div>

{% endblock %}

academic_manager/main/templates/login.html
{% extends "base.html" %}
{% block title %}Login page{% endblock %}
{% block content %}

<div class="card">
    <h5 class="card-header">Join Today</h5>
    <div class="card-body">

        <form action="#" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">

                <!-- Email -->
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>

                <!-- Password -->
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control") }}
                    {% endif %}
                </div>

                <!-- Remember -->
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-input-label") }}
                </div>
            </fieldset>

            <div class="form-group">
                <!-- Submit -->
                {{ form.submit(class="btn btn-outline-info") }}

                <!-- Forgot Password -->
                <small class="text-muted ml-2">
                    <a href="{{ url_for('main.reset_password_request') }}">Forgot Password?</a>
                </small>
            </div>

        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{{ url_for('main.register') }}">Sign Up Now</a>
            </small>

        </div>
    </div>
</div>

{% endblock %}

academic_manager/main/templates/profile.html
{% extends "base.html" %}
{% block title %}{{ current_user.first_name }}'s Profile{% endblock %}
{% block content %}
<div class="card">
    <h4 class="card-header">My Profile</h4>
    <div class="card-body">
        <div class="media">
            <img class="rounded-circle profile-img" src="{{ image_file }}" alt="profile picture">
            <div class="media-body">
                <h2>{{ user.full_name }}</h2>
                <p class="text-secondary">{{ user.email }}
                    <br>{{ user.gender }}, {{ user.role }}
                    <br>Last Seen at {{ user.last_seen.strftime('%H:%M %b %d, %Y') }}</p>
                {% if current_user==user or current_user.is_admin %}
                    <a href="{{ url_for('main.update_user_profile', user_id=user.id) }}"
                       class="btn btn-success btn-sm"><i class="fas fa-pencil-alt mr-2"></i>Update</a>

                    <!-- Button trigger modal -->
                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal">
                        <i class="fas fa-trash-alt mr-2"></i>Delete</button>

                <p>
                    <a href="{{ url_for('main.profile_picture_gallery') }}"><i class="fas fa-camera-retro mr-2 mt-5"></i>You can take a look at our default profile pictures</a>
                </p>
                {% endif %}
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete {{ user.email }}?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a type="button" class="btn btn-danger"
                href="{{ url_for('main.delete_user', user_id=user.id) }}">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

academic_manager/main/templates/profile_pic_gallery.html
{% extends "base.html" %}
{% block title %}Pic a pic{% endblock %}
{% block content %}

<h3><i class="fas fa-camera-retro mr-2 fa-lg"></i>Pick a pic</h3>
<div class="content-section textalign-center">
    <form action="#" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <!-- Images -->
            <div class="form-group">
                {% for subfield in form.images %}
                <div class="form-check form-check-inline">
                    {{ subfield(class="form-check-input") }}
                    <img class="rounded-circle view-img mr-4 my-3"
                         src="{{ url_for('static', filename='profile_pics/default/' + subfield.data) }}">

                </div>
                {% endfor %}
            </div>
        </fieldset>

        <!-- Submit -->
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>


{% endblock %}

academic_manager/main/templates/register.html
{% extends "base.html" %}
{% block title %}Register page{% endblock %}
{% block content %}
<div class="card">
    <h5 class="card-header">Join Today</h5>
    <div class="card-body">

        <form action="#" method="POST">
            {{ form.hidden_tag() }}

            <fieldset class="form-group">

                <div class="row">
                    <!-- First Name -->
                    <div class="form-group col">
                        {{ form.first_name.label(class="form-control-label") }}
                        {% if form.first_name.errors %}
                            {{ form.first_name(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.first_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.first_name(class="form-control") }}
                        {% endif %}
                    </div>

                    <!-- Last Name -->
                    <div class="form-group col">
                        {{ form.last_name.label(class="form-control-label") }}
                        {% if form.last_name.errors %}
                            {{ form.last_name(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.last_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.last_name(class="form-control") }}
                        {% endif %}
                    </div>
                </div>

                <!-- Email -->
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                        <small class="form-text text-muted">We'll never share your email with anyone else.</small>
                    {% endif %}
                </div>

                <div class="row">
                    <!-- Password -->
                    <div class="form-group col">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control") }}
                            <small class="form-text text-muted">Must be 8-20 characters long.</small>
                        {% endif %}
                    </div>

                    <!-- Confirm Password -->
                    <div class="form-group col">
                        {{ form.confirm_password.label(class="form-control-label") }}
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.confirm_password(class="form-control") }}
                        {% endif %}
                    </div>
                </div>

                <!-- Gender -->
                <div class="form-group">
                    <div>{{ form.gender.label(class="form-control-label") }}:</div>
                    {% for subfield in form.gender %}
                        <div class="form-check form-check-inline">
                            {{ subfield(class="form-check-input") }}
                            {{ subfield.label(class="form-check-label") }}
                        </div>
                    {% endfor %}
                </div>

                <!-- Role -->
                <div class="form-group">
                    <div>{{ form.role.label(class="form-control-label") }}:</div>
                    {% for subfield in form.role %}
                        <div class="form-check form-check-inline">
                            {{ subfield(class="form-check-input") }}
                            {{ subfield.label(class="form-check-label") }}
                        </div>
                    {% endfor %}
                </div>
            </fieldset>

            <!-- Submit -->
            <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>

        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{{ url_for('main.login') }}">Sign In</a>
            </small>

        </div>
    </div>
</div>

{% endblock %}

academic_manager/main/templates/reset_password_request.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div class="card">
    <h5 class="card-header">Reset Password</h5>
    <div class="card-body">
        <form action="#" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <!-- Email -->
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control") }}
                    <small class="form-text text-muted">We'll never share your email with anyone else.</small>
                    {% endif %}
                </div>
            </fieldset>
                <!-- Submit -->
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
        </form>
    </div>
</div>

{% endblock %}

academic_manager/main/templates/reset_password_token.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div class="card">
    <h5 class="card-header">Reset Password</h5>
    <div class="card-body">
        <form action="#" method="POST">
            {{ form.hidden_tag() }}

            <fieldset class="form-group">
                <!-- Password -->
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control") }}
                    <small class="form-text text-muted">Must be 8-20 characters long.</small>
                    {% endif %}
                </div>

                <!-- Confirm Password -->
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.confirm_password(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>
            <!-- Submit -->
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

academic_manager/main/templates/update_user_profile.html
{% extends "base.html" %}
    {% block title %}Update {{ user.user_name }}'s Profile{% endblock %}
{% block content %}
<div class="card">
    <h5 class="card-header">Update {{ user.full_name }}'s Profile</h5>
    <div class="card-body">

        <form action="#" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}

            <fieldset class="form-group">

                <div class="row">

                    <!-- First Name -->
                    <div class="form-group col">
                        {{ form.first_name.label(class="form-control-label") }}
                        {% if form.first_name.errors %}
                            {{ form.first_name(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.first_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.first_name(class="form-control") }}
                        {% endif %}
                    </div>

                    <!-- Last Name -->
                    <div class="form-group col">
                        {{ form.last_name.label(class="form-control-label") }}
                        {% if form.last_name.errors %}
                            {{ form.last_name(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.last_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.last_name(class="form-control") }}
                        {% endif %}
                    </div>
                </div>

                <!-- Email -->
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                        <small class="form-text text-muted">We'll never share your email with anyone else.</small>
                    {% endif %}
                </div>

                <!-- Picture -->
                <div class="form-group">
                    {{ form.picture.label() }}:
                    {{ form.picture(class="form-control-file  form-control-sm") }}
                    {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span><br>
                            {% endfor %}
                    {% endif %}
                </div>

                <!-- Gender -->
                <div class="form-group">
                    <div>{{ form.gender.label(class="form-control-label") }}:</div>
                    {% for subfield in form.gender %}
                        <div class="form-check form-check-inline">
                            {{ subfield(class="form-check-input") }}
                            {{ subfield.label(class="form-check-label") }}
                        </div>
                    {% endfor %}
                </div>

            </fieldset>

            <!-- Submit -->
            <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}