academic_manager/admin/routes.py
from flask import redirect, url_for, render_template, request, session, flash, Blueprint
from academic_manager.extensions import db, restricted
from academic_manager.models import *

admin = Blueprint('admin', __name__, template_folder="templates", url_prefix="/admin")


@admin.route("/", methods=['POST', 'GET'])
def admin_panel():
    student_list = Student.query.all()
    teacher_list = Teacher.query.all()
    courses_list = Course.query.all()
    return render_template("admin.html", student_list=student_list, teacher_list=teacher_list,
                           courses_list=courses_list)


@admin.route("/admin_students/")
@restricted(role=["admin"])
def admin_students():
    student_list = Student.query.all()
    return render_template("admin_students.html", student_list=student_list)


@admin.route("/admin_teachers/")
@restricted(role=["admin"])
def admin_teachers():
    teacher_list = Teacher.query.all()
    return render_template("admin_teachers.html", teacher_list=teacher_list)


@admin.route("/admin_courses/")
@restricted(role=["admin"])
def admin_courses():
    courses_list = Course.query.order_by(Course.course_name).all()
    return render_template("admin_courses.html", courses_list=courses_list)


@admin.route("/teacher_approval/<string:action>/<int:user_id>/")
@restricted(role=["admin"])
def teacher_approval(user_id, action):
    current_teacher = Teacher.query.get(user_id)
    if action == "approve":
        current_teacher.approved = True
        flash(f"{current_teacher.email} has been approved", "success")
    elif action == "disapprove":
        current_teacher.approved = False
        flash(f"{current_teacher.email} has been disapproved", "warning")
    db.session.commit()
    return redirect(request.referrer)


@admin.route("/search=?/", methods=['POST'])
@restricted(role=["admin"])
def admin_search_panel():
    # todo can add smarter filters to search in db
    if request.method == "POST":
        value = request.form["search"]
        student = Student.query.filter_by(user_name=value).first()
        teacher = Teacher.query.filter_by(user_name=value).first()
        course = Course.query.filter_by(course_name=value).first()

        if student:
            return redirect(url_for('students.watch_student', student_id=student.id))
        elif teacher:
            return redirect(url_for('teachers.watch_teacher', teacher_id=teacher.id))
        elif course:
            return redirect(url_for('courses.course_dashboard_teacher', course_id=course.id))

        flash("There is no such value!", "warning")
        return redirect(request.referrer)

academic_manager/admin/templates/admin.html
{% extends "base.html" %}
{% block title %}Admin Page{% endblock %}
{% block content %}
<a href="{{ url_for('main.main_db_init') }}" class="btn btn-danger"><i class="fas fa-database mr-2"></i>db init</a>
<br>
<br>
<div class="card">
    <h5 class="card-header">Student</h5>
    <div class="card-body">
        <table style="width:100%">
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Gender</th>
                <th>Action</th>
            </tr>

            {% for student in student_list %}
            <tr>
                <td>{{ student.full_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.role }}</td>
                <td>{{ student.gender }}</td>
                <td><a href="{{ url_for('students.watch_student', user_id=student.id) }}"
                       class="badge badge-primary">Watch</a>
                    <a href="#" class="badge badge-success">Update</a>
                    <a href="{{ url_for('main.delete_user', user_id=student.id) }}"
                       class="badge badge-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
<br>
<div class="card">
    <h5 class="card-header">Teacher</h5>
    <div class="card-body">
        <table style="width:100%">
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Gender</th>
                <th>Approval</th>
                <th>Action</th>
            </tr>

            {% for teacher in teacher_list %}
            <tr>
                <td>{{ teacher.full_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.gender }}</td>
                <td>
                    {% if teacher.approved %}
                    <a href="{{ url_for('admin.teacher_approval', user_id=teacher.id, action='disapprove') }}"
                       class="badge badge-warning">Disapprove</a>
                    {% else %}
                    <a href="{{ url_for('admin.teacher_approval' ,user_id=teacher.id, action='approve') }}"
                       class="badge badge-info">Approve</a>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ url_for('teachers.watch_teacher', user_id=teacher.id) }}"
                       class="badge badge-primary">Watch</a>
                    <a href="{{ url_for('main.update_user_profile', user_id=teacher.id) }}"
                       class="badge badge-success">Update</a>
                    <a href="{{ url_for('main.delete_user', user_id=teacher.id) }}"
                       class="badge badge-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
<br>
<div class="card">
    <h5 class="card-header">Courses</h5>
    <div class="card-body">
        <table style="width:100%">
            <tr>
                <th>Course Name</th>
                <th>Teacher</th>
                <th>Students</th>
                <th>Action</th>
            </tr>

            {% for course in courses_list %}
            <tr>
                <td>{{ course.course_name }}</td>
                <td>{{ course.lecturer.full_name }}</td>
                <td>{{ course.enrollment|length }}</td>
                <td><a href="{{ url_for('courses.course_dashboard', course_id=course.id) }}"
                       class="badge badge-info">Dashboard</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

academic_manager/admin/templates/admin_courses.html
{% extends "base.html" %}
{% block title %}Admin Page - Courses{% endblock %}
{% block content %}
<div class="card">
    <h5 class="card-header">Admin Panel - Manage Courses:</h5>
    <div class="card-body">
        <table class="table" style="width:100%">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Course Name</th>
                <th scope="col">Teacher</th>
                <th scope="col">Participants</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for course in courses_list %}
            <tr>
                <td scope="row">{{ loop.index }}</td>
                <td scope="row">{{ course.course_name }}</td>
                <td scope="row">{{ course.lecturer.full_name }}</td>
                <td scope="row">{{ course.enrollment|length }}</td>
                <td scope="row"><a href="{{ url_for('courses.course_dashboard', course_id=course.id) }}"
                       class="badge badge-info">Dashboard</a>
                    <a href="{{ url_for('courses.delete_course', course_id=course.id) }}"
                       class="badge badge-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <br>
    </div>
</div>

{% endblock %}

academic_manager/admin/templates/admin_students.html
{% extends "base.html" %}
{% block title %}Admin Page - Students{% endblock %}
{% block content %}


<div class="card">
    <h5 class="card-header">Admin Panel - Manage Students:</h5>
    <div class="card-body">
        <table class="table" style="width:100%">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Gender</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
                {% for student in student_list %}
                <tr>
                    <td scope="row">{{ loop.index }}</td>
                    <td scope="row">{{ student.full_name }}</td>
                    <td scope="row">{{ student.email }}</td>
                    <td scope="row">{{ student.gender }}</td>
                    <td scope="row"><a href="{{ url_for('students.watch_student', user_id=student.id) }}"
                           class="badge badge-primary">Watch</a>
                        <a href="{{ url_for('main.update_user_profile', user_id=student.id) }}"
                           class="badge badge-success">Update</a>
                        <a href="{{ url_for('main.delete_user', user_id=student.id) }}"
                           class="badge badge-danger">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br><br>

    </div>
</div>
{% endblock %}

academic_manager/admin/templates/admin_teachers.html
{% extends "base.html" %}
{% block title %}Admin Page - Teachers{% endblock %}
{% block content %}
<div class="card">
    <h5 class="card-header">Admin Panel - Mange Teachers:</h5>
    <div class="card-body">
        <table class="table" style="width:100%">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Gender</th>
                <th scope="col">Approval</th>
                <th scope="col"></th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for teacher in teacher_list %}
            <tr>
                <td scope="row">{{ loop.index }}</td>
                <td scope="row">{{ teacher.full_name }}</td>
                <td scope="row">{{ teacher.email }}</td>
                <td scope="row">{{ teacher.gender }}</td>
                <td scope="row">{{ teacher.approved }}</td>
                <td scope="row">
                    {% if teacher.approved %}
                    <a href="{{ url_for('admin.teacher_approval', user_id=teacher.id, action='disapprove') }}"
                       class="badge badge-warning">Disapprove {{ teacher.user_name }}</a>
                    {% else %}
                    <a href="{{ url_for('admin.teacher_approval' ,user_id=teacher.id, action='approve') }}"
                       class="badge badge-info">Approve {{ teacher.user_name }}</a>
                    {% endif %}
                </td>
                <td scope="row">
                    <a href="{{ url_for('teachers.watch_teacher', user_id=teacher.id) }}"
                       class="badge badge-primary">Watch</a>
                    <a href="{{ url_for('main.update_user_profile', user_id=teacher.id) }}"
                       class="badge badge-success">Update</a>
                    <a href="{{ url_for('main.delete_user', user_id=teacher.id) }}"
                       class="badge badge-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <br>
    </div>
</div>
{% endblock %}