academic_manager/students/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField
from wtforms.validators import DataRequired


class NewEnrollmentForm(FlaskForm):
    enrollment = SelectField('Courses', validators=[DataRequired()], coerce=int, validate_choice=False)
    submit = SubmitField('Enroll Now')

academic_manager/admin/routes.py
from flask import redirect, url_for, render_template, request, session, flash, Blueprint
from academic_manager.extensions import db, restricted
from academic_manager.models import *

admin = Blueprint('admin', __name__, template_folder="templates", url_prefix="/admin")


@admin.route("/", methods=['POST', 'GET'])
def admin_panel():
    student_list = Student.query.all()
    teacher_list = Teacher.query.all()
    courses_list = Course.query.all()
    return render_template("admin.html", student_list=student_list, teacher_list=teacher_list,
                           courses_list=courses_list)


@admin.route("/admin_students/")
@restricted(role=["admin"])
def admin_students():
    student_list = Student.query.all()
    return render_template("admin_students.html", student_list=student_list)


@admin.route("/admin_teachers/")
@restricted(role=["admin"])
def admin_teachers():
    teacher_list = Teacher.query.all()
    return render_template("admin_teachers.html", teacher_list=teacher_list)


@admin.route("/admin_courses/")
@restricted(role=["admin"])
def admin_courses():
    courses_list = Course.query.order_by(Course.course_name).all()
    return render_template("admin_courses.html", courses_list=courses_list)


@admin.route("/teacher_approval/<string:action>/<int:user_id>/")
@restricted(role=["admin"])
def teacher_approval(user_id, action):
    current_teacher = Teacher.query.get(user_id)
    if action == "approve":
        current_teacher.approved = True
        flash(f"{current_teacher.email} has been approved", "success")
    elif action == "disapprove":
        current_teacher.approved = False
        flash(f"{current_teacher.email} has been disapproved", "warning")
    db.session.commit()
    return redirect(request.referrer)


@admin.route("/search=?/", methods=['POST'])
@restricted(role=["admin"])
def admin_search_panel():
    # todo can add smarter filters to search in db
    if request.method == "POST":
        value = request.form["search"]
        student = Student.query.filter_by(user_name=value).first()
        teacher = Teacher.query.filter_by(user_name=value).first()
        course = Course.query.filter_by(course_name=value).first()

        if student:
            return redirect(url_for('students.watch_student', student_id=student.id))
        elif teacher:
            return redirect(url_for('teachers.watch_teacher', teacher_id=teacher.id))
        elif course:
            return redirect(url_for('courses.course_dashboard_teacher', course_id=course.id))

        flash("There is no such value!", "warning")
        return redirect(request.referrer)

academic_manager/main/routes.py
from flask import redirect, render_template, request, flash, Blueprint, url_for, current_app
from flask_login import login_user, current_user, logout_user, login_required
from academic_manager.extensions import bcrypt, restricted
from academic_manager.main.forms import (RegistrationForm, LoginForm, UpdateUserForm, ProfilePictureForm,
                                         ResetPasswordForm, ResetPasswordRequestForm)
from academic_manager.main.utilities import *
from academic_manager.students.utilities import *
from datetime import datetime
from academic_manager.models import User
from academic_manager.main.db_init import init_db

main = Blueprint('main', __name__, template_folder="templates")


@main.route("/init_db")
def main_db_init():
    init_db()
    return redirect(url_for("main.home"))


@main.route("/")
@main.route("/home/")
def home():
    if current_user.is_authenticated:
        best_student = get_best_student()
        current_date = datetime.now()
        return render_template("home.html", best_student=best_student, current_date=current_date)
    else:
        return render_template("index.html")


@main.route("/login/", methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        flash("Already logged in!", "warning")
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()

        # Validate the password if the user exist
        if user and bcrypt.check_password_hash(user.password, form.password.data):

            # Check if teacher ia approved by the admin
            if user.is_teacher and not user.approved:
                flash(f"{user.email} is not approved yet by the admin", "danger")
                return redirect(url_for("main.home"))

            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash("Logged in successfully!", "success")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))

        else:
            flash("The Email or Password is invalid", "danger")
            return redirect(url_for("main.login"))

    return render_template("login.html", form=form)


@main.route("/register/", methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        flash("Already logged in!", "warning")
        return redirect(url_for("main.home"))
    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        make_new_user(form.email.data, form.first_name.data, form.last_name.data,
                      hashed_password, form.gender.data, form.role.data)
        flash(f'Account created for {form.first_name.data}! You can login now', 'success')
        return redirect(url_for('main.login'))

    return render_template('register.html', form=form)


@main.route("/logout/")
@login_required
def logout():
    current_user.update_last_seen()
    logout_user()
    return redirect(url_for("main.home"))


@main.route("/profile/<int:user_id>")
@login_required
def profile(user_id):
    user = User.query.get_or_404(user_id)
    image_file = url_for('static', filename='profile_pics/' + user.profile_img)
    return render_template('profile.html', user=user, image_file=image_file)


@main.route("/update/<int:user_id>/", methods=['POST', 'GET'])
@restricted(role=["admin", "current_user"])
def update_user_profile(user_id):
    form = UpdateUserForm(user_id=user_id)
    user = User.query.get_or_404(user_id)

    if form.validate_on_submit():

        # Profile picture handling
        if form.picture.data:

            # Resize and save picture in users folder
            pic_file = save_picture(form.picture.data)

            # Removes the previous image from the repository
            remove_profile_picture(user.profile_img)
            user.profile_img = pic_file

        name = user.first_name
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.email = form.email.data.lower()
        user.gender = form.gender.data
        db.session.commit()

        flash(f"{name}'s profile has been updated!", 'success')
        return redirect(url_for('main.profile', user_id=user_id))

    elif request.method == 'GET':
        form.first_name.data = user.first_name
        form.last_name.data = user.last_name
        form.email.data = user.email
        form.gender.data = user.gender

    return render_template('update_user_profile.html', user=user, form=form)


@main.route("/profile-pic-gallery/", methods=['POST', 'GET'])
@login_required
def profile_picture_gallery():
    item_lst = os.listdir(os.path.join(current_app.root_path, 'static/profile_pics/default'))
    form = ProfilePictureForm()

    if form.validate_on_submit():
        remove_profile_picture(current_user.profile_img)
        current_user.profile_img = "default/" + form.images.data
        db.session.commit()

        flash('Your profile image has been updated!', 'success')
        return redirect(url_for('main.profile', user_id=current_user.id))

    elif request.method == "GET":
        form.images.choices = item_lst

    return render_template('profile_pic_gallery.html', form=form)


@main.route("/delete_user/<int:user_id>")
@restricted(role=["admin", "current_user"])
def delete_user(user_id):
    user_to_del = User.query.get_or_404(user_id)

    # User deleting his profile
    if current_user.id == user_id:
        logout_user()
        user_to_del.delete_from_db()
        flash("Your account has been deleted", "success")
        return redirect(url_for("main.home"))

    # Admin deleting other user profile
    if current_user.is_admin:
        flash(f"{user_to_del.email} has been deleted", "success")
        is_teacher = user_to_del.is_teacher
        user_to_del.delete_from_db()
        return redirect(url_for("admin.admin_teachers")) if is_teacher \
            else redirect(url_for("admin.admin_students"))


@main.route("/reset-password/", methods=['POST', 'GET'])
def reset_password_request():
    if current_user.is_authenticated:
        flash("Already logged in!", "warning")
        return redirect(url_for("main.home"))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_password_email(user)
        flash("An email has been sent to your account with password reset instructions.", "info")
        return redirect(url_for("main.login"))

    return render_template('reset_password_request.html', form=form)


@main.route("/reset-password/<token>/", methods=['POST', 'GET'])
def reset_password_token(token):
    if current_user.is_authenticated:
        flash("Already logged in!", "warning")
        return redirect(url_for("main.home"))

    user = User.verify_reset_password_token(token)
    if not user:
        flash("Your token is invalid or has expired", "warning")
        return redirect(url_for("main.reset_password_request"))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You can login now', 'success')
        return redirect(url_for('main.login'))
    return render_template('reset_password_token.html', form=form)

academic_manager/students/routes.py
from flask import redirect, url_for, render_template, request, flash, Blueprint, abort
from flask_login import current_user
from academic_manager.extensions import restricted
from academic_manager.students.forms import NewEnrollmentForm
from academic_manager.students.utilities import *

students = Blueprint('students', __name__, template_folder="templates", url_prefix="/students")


@students.route("/")
def student():
    return redirect(url_for("main.home"))


@students.route("/manage_courses/")
@restricted(role=["student"])
def manage_courses_student():
    return render_template("student_courses.html", student=current_user)


@students.route("/new_enrollment/", methods=['POST', 'GET'])
@restricted(role=["student"])
def new_enrollment():
    form = NewEnrollmentForm()

    # create courses to enroll list for the Select Field (choices)
    current_courses_id_lst = current_user.get_courses_id_lst()
    courses_to_enroll = [(course.id, course.course_name + " (" + course.lecturer.full_name + ")")
                         for course in Course.query.all()
                         if course.id not in current_courses_id_lst]
    courses_to_enroll.insert(0, ('0', "Choose Course:"))

    if request.method == "GET":
        form.enrollment.choices = courses_to_enroll
        return render_template("new_enrollment.html", form=form, courses=courses_to_enroll)

    if form.validate_on_submit():
        course_id = form.enrollment.data
        course = Course.query.get(course_id)
        make_new_enrollment(current_user.id, course_id)
        flash(f"You have successfully enrolled for {course.course_name} ", "success")

    return redirect(url_for('students.new_enrollment'))


@students.route("/remove_enrollment/<int:user_id>/<int:enrollment_id>")
@restricted(role=["admin", "teacher", "current_user"])
def remove_enrollment(user_id, enrollment_id):
    enroll_to_del = Enrollment.query.get(enrollment_id)
    current_student = Student.query.get(user_id)
    current_course = enroll_to_del.course
    if enroll_to_del:
        if current_user.is_teacher and current_course.lecturer != current_user:
            abort(403)
        else:
            enroll_to_del.delete_from_db()
            flash(f"{current_student.full_name} has been removed from {current_course.course_name}", "success")
            return redirect(request.referrer)


@students.route("/watch/<int:user_id>")
@restricted(role=["admin", "teacher"])
def watch_student(user_id):
    student_profile = Student.query.filter_by(id=user_id).first_or_404()
    image_file = url_for('static', filename='profile_pics/' + student_profile.profile_img)
    return render_template("watch_student.html", student=student_profile, image_file=image_file)

academic_manager/teachers/routes.py
from flask import redirect, url_for, render_template, request, session, flash, Blueprint
from flask_login import current_user
from academic_manager.extensions import db, restricted
from academic_manager.models import Teacher, Course, Enrollment
from academic_manager.main.utilities import *

teachers = Blueprint('teachers', __name__, template_folder="templates", url_prefix="/teachers")


@teachers.route("/")
def teacher():
    return redirect(url_for("main.home"))


@teachers.route("/manage_courses/")
@restricted(role=["teacher"])
def manage_courses_teacher():
    return render_template("teacher_courses.html", teacher=current_user)


@teachers.route("/watch/<int:user_id>")
@restricted(role=["admin"])
def watch_teacher(user_id):
    teacher_profile = Teacher.query.filter_by(id=user_id).first_or_404()
    image_file = url_for('static', filename='profile_pics/' + teacher_profile.profile_img)
    return render_template("watch_teacher.html", teacher=teacher_profile, image_file=image_file)

academic_manager/templates/admin.html
{% extends "base.html" %}
{% block title %}Admin Page{% endblock %}
{% block content %}
    <h5 class="card-header">Admin</h5>
    <div class="card-body">
        <a href="{{ url_for('add_course') }}" class="btn btn-primary" >Add Course</a>
        <table style="width:100%">
          <tr>
              <th colspan="4"><h2>Student</h2></th>
          </tr>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Action</th>
          </tr>

          {% for student in student_list %}
              <tr>
                <td>{{ student.user_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.password }}</td>
                <td><a href="#" class="badge badge-primary">Watch</a>
                    <a href="#" class="badge badge-success">Update</a>
                    <a href="#" class="badge badge-danger">Delete</a>
                </td>
              </tr>
          {% endfor %}
        <tr><th colspan="4"><br></tr>
          <tr>
              <th colspan="4"><br></th>
          </tr>
          <tr>
              <th colspan="4"><h2>Teacher</h2></th>
          </tr>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Action</th>
          </tr>

          {% for teacher in teacher_list %}
              <tr>
                <td>{{ teacher.user_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.password }}</td>
                 <td>
                     <a href="#" class="badge badge-primary">Watch</a>
                    <a href="#" class="badge badge-success">Update</a>
                    <a href="#" class="badge badge-danger">Delete</a>
                </td>
              </tr>
          {% endfor %}
        </table>

        <br><br>
        <table style="width:100%">
          <tr>
              <th colspan="4"><h2>Courses</h2></th>
          </tr>
          <tr>
            <th>Course Name</th>
            <th>Teacher</th>
            <th>Students</th>
            <th>Action</th>
          </tr>

          {% for course in courses_list %}
              <tr>
                <td>{{ course.course_name }}</td>
                <td>{{ course.lecturer.user_name }}</td>
                <td>  </td>
                <td><a href="#" class="badge badge-primary">Watch</a>
                    <a href="#" class="badge badge-success">Update</a>
                    <a href="#" class="badge badge-danger">Delete</a>
                </td>
              </tr>
          {% endfor %}
        </table>
    </div>
{% endblock %}

academic_manager/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/main.css') }}">

    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">

    body {
      background: #ffffff;
      color: #333333;
    }

    .content-section {
      background: #ffffff;
      padding: 10px 20px;
      border: 1px solid #aaaaaa;
      border-radius: 3px;
      margin-bottom: 20px;
    }

    .profile-img {
      height: 125px;
      width: 125px;
      margin-right: 20px;
      margin-bottom: 16px;
    }

    .view-img {
      height: 150px;
      width: 150px;
      margin-right: 20px;
      margin-bottom: 16px;
    }

    .card {
      border: 1px solid #aaaaaa;
    }

    .btn-del :hover {
        color: #cc2565;
    }

    .btn-edit :hover {
        color: #6445ff;
    }

    .my-btn {
        color: #4f4f49;
    }

    .article-title {
      color: #444444;
    }

    a.article-title:hover {
      color: #428bca;
      text-decoration: none;
    }

    .article-content {
      white-space: pre-line;
    }

    .crop {
        white-space: nowrap;
        max-width: 600px;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .article-img {
      height: 65px;
      width: 65px;
      margin-right: 16px;
    }

    .article-metadata {
      padding-bottom: 1px;
      margin-bottom: 4px;
      border-bottom: 1px solid #e3e3e3
    }

    .article-metadata a:hover {
      color: #333;
      text-decoration: none;
    }

    .article-svg {
      width: 25px;
      height: 25px;
      vertical-align: middle;
    }



    </style>
</head>
<body>
<header class="site-header">

    <!-- Site Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('main.home') }}"><i class="fas fa-user-graduate mr-2 ml-1"></i>Academic
            Manager </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <div class="navbar-nav mr-auto">
                <a class="nav-link" href="{{ url_for('main.home') }}"><i class="fas fa-home mr-2"></i>Home</a>
                <a class="nav-link" href="{{ url_for('admin.admin_panel') }}"><i class="fas fa-info-circle mr-2"></i>About</a>
            </div>

            <!-- Site Navbar | Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-link" href="{{ url_for('main.profile', user_id=current_user.id) }}">
                    <i class="fas fa-user-circle"></i> Profile</a>
                <a class="nav-link" href="{{ url_for('main.logout') }}"><i class="fas fa-sign-out-alt mr-2"></i>Log Out</a>
                {% else %}
                <a class="nav-link" href="{{ url_for('main.login') }}"><i class="fas fa-sign-in-alt mr-2"></i>Login</a>
                <a class="nav-link" href="{{ url_for('main.register') }}"><i class="fas fa-user-plus mr-2"></i>Register</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% if current_user.is_authenticated %}
    <nav class="navbar navbar-expand-md navbar-light bg-light">

        <!-- Admin Navbar -->
        {% if current_user.is_admin %}
        <a class="navbar-brand">Admin</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('admin.admin_panel') }}">Panel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('admin.admin_students') }}">Students</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('admin.admin_teachers') }}">Teachers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('admin.admin_courses') }}">Courses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('courses.add_course') }}">Add Course</a>
            </li>
        </ul>
        <!-- Admin Search -->
        <form action="{{ url_for('admin.admin_search_panel') }}" method="post" class="form-inline">
            <input class="form-control mr-sm-2" name="search" type="search"
                   placeholder="Search by User Name" aria-label="Search" required>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

        <!-- Teacher Navbar -->

        {% elif current_user.is_teacher %}
        <a class="navbar-brand">Teacher</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('teachers.manage_courses_teacher') }}">Manage Courses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('courses.add_course') }}">Add Course</a>
            </li>
        </ul>

        <!-- Student Navbar -->
        {% elif current_user.is_student %}
        <a class="navbar-brand">Student</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('students.manage_courses_student') }}">Manage Courses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('students.new_enrollment') }}">New Enrollment</a>
            </li>
        </ul>
        {% endif %}
    </nav>
    {% endif %}

</header>

<main role="main" class="container">

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, msg in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show mt-3" role="alert">
        <strong>info: </strong>{{msg}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="col-md-13 mt-4 mb-3">
        {% block content %}{% endblock %}
    </div>


</main>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
      integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz"
      crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>

academic_manager/templates/home.html
{% extends "base.html" %}
{% block title %}Home page{% endblock %}

{% block content %}


    {% if session["type"] %}
    <h5 class="card-header">Welcome {{ session["user_name"] }}</h5>
    <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        {% for i in range(5) %}
        <p>.</p>
        {% endfor %}

    </div>
    {% else %}
    <h5 class="card-header">Welcome</h5>
    <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="{{ url_for('login') }}" class="btn btn-primary">Login</a>
        <a href="{{ url_for('sign_up') }}" class="btn btn-primary">Sign up</a><br>
    </div>
    {% endif %}


{% endblock %}

academic_manager/templates/student.html
{% extends "base.html" %}
{% block title %}Student Page{% endblock %}
{% block content %}
    <h5 class="card-header">Student</h5>
    <div class="card-body">
        <table style="width:100%">
          <tr>
              <th colspan="4"><h2>Your details:</h2></th>
          </tr>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Action</th>
          </tr>
              <tr>
                <td>{{ student.user_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.password }}</td>
                <td>
                    <a href="#" class="badge badge-success">Update</a>
                    <a href="#" class="badge badge-danger">Delete</a>
                </td>
              </tr>
        </table>
        <br><br>
        <div>
            <h3>Courses you have:</h3>
            <ul>
                {% for enrollment in student.enrollment %}
                    <li>{{ enrollment.course.course_name }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

academic_manager/templates/teacher.html
{% extends "base.html" %}
{% block title %}Teacher Page{% endblock %}
{% block content %}
    <h5 class="card-header">teacher</h5>
    <div class="card-body">
        <table style="width:100%">
          <tr>
              <th colspan="4"><h2>Your details:</h2></th>
          </tr>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Action</th>
          </tr>
              <tr>
                <td>{{ teacher.user_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.password }}</td>
                <td>
                    <a href="#" class="badge badge-success">Update</a>
                    <a href="#" class="badge badge-danger">Delete</a>
                </td>
              </tr>
        </table>
        <br><br>
        <div>
            <h3>Courses you teach:</h3>
            <ul>
                {% for course in teacher.course %}
                    <li>{{ course.course_name }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}